# Schema for the configuration files of the Helios theme.

helios_responsive.settings:
  type: theme_settings
  label: 'Helios settings'
  mapping:
    # @todo Module-specific settings should be defined by the module:
    #   https://drupal.org/node/2235901.
    helios_responsive_enable_banner_block:
      type: boolean
      label: 'Enable banner content'
    helios_responsive_banner_title:
      type: string
      label: 'Banner title'
    helios_responsive_banner_description:
      type: string
      label: 'Banner description'

helios_responsive.breakpoints:
  type: theme_breakpoints_default
  label: 'Helios breakpoints'
